import { Inter } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light">
      <body className="{inter.className}">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
